name: Integration Workflow

on:
  pull_request:
    branches:
      - dev
      - topic/*

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
