name: Integration Workflow

on:
  pull_request:
    branches:
      - dev
      - topic/*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
        
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: sports-hub-ui-cache
      with:
        path: ~/.npm
        key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ env.cache-name }}-

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test
